kind: pipeline
type: docker
name: default

clone:
  depth: 50
  
steps:
- name: ping
  image: redis
  commands:
  - redis-cli -h cache ping
  - redis-cli -h queue ping

services:
- name: cache
  image: redis

services:
- name: queue
  image: redis

services:
- name: mariadb
  image: mariadb
